<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RIPLBRD50" ignored="0" name="Default test" tests="7" failures="2" timestamp="28 Nov 2017 07:27:35 GMT" time="39.046" errors="0">
  <testcase name="verifiyLoginWithDifferentRecords" time="15.016" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn&amp;apos;t finish within the time-out 15000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn't finish within the time-out 15000
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at com.test.automation.UIAutomation.uiActions.LoginPage.loginToApplication(LoginPage.java:70)
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="15.002" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn&amp;apos;t finish within the time-out 15000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn't finish within the time-out 15000
	at java.lang.Thread.interrupt(Thread.java:916)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.test.automation.UIAutomation.testBase.TestBase.waitForVisitibilty(TestBase.java:270)
	at com.test.automation.UIAutomation.testBase.TestBase.isElementPresent(TestBase.java:298)
	at com.test.automation.UIAutomation.uiActions.LoginPage.loginToApplication(LoginPage.java:66)
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.005" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.004" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.003" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.005" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.004" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
</testsuite> <!-- Default test -->
